Fix/feedback changes 3
Polkadex-Substrate/polkadex-mobile-app pull request #252
Opened 2022-11-08 14:05 UTC by driels97

This PR pushes some minor changes to the app request by @pavankanteti:

- [x] 'Already' spelling to be corrected on Login screen
- [x] 'Wallets' should be called 'Accounts'
- [x] Scan QR code page should say 'Looks like you don't have any trading accounts' >> subtext: Scan your trading account QR code or enter the mnemonic seed phrase to import your trading account.
- [x] 'Import wallet' should be changed to 'Enter Mnemonic'
- [x] Token screen should show 'Deposit' icon next to withdraw. When clicked on 'Deposit' icon, text should say >> 'Deposits are not supported currently on the mobile app. Add more funds to your account using Orderbook webapp.'
- [x] Withdraw page should say 'Funding Account' instead of Main wallet.
- [x] Remove graph from 'Withdraw' screen
- [x] Pricing length on graph tab should show '0.0001' to be in sync with webapp
- [x] Bottom options tab should always be fixed

2022-11-08 19:51 UTC, serhii-temchenko requested changes

2022-11-08 19:51 UTC, serhii-temchenko commented on lib/features/landing/presentation/sub_views/balance_tab_view.dart
> +                          "Looks like you don't have any trading acounts",
Still missing `c` in `acounts`...

2022-11-08 19:51 UTC, serhii-temchenko commented on lib/features/app_settings_info/screens/my_account_screen.dart
> +                                    'Kas Pintxuki',
Is it should be like this?

2022-11-08 19:51 UTC, serhii-temchenko commented on lib/features/app_settings_info/screens/my_account_screen.dart
> +                          'Polkadex does not store any data , this is just a temporary data, if you uninstall the Polkadex App your name and referral ID will be removed.',
Extra space between `data ,`

2022-11-08 23:03 UTC, driels97 commented on lib/features/app_settings_info/screens/my_account_screen.dart
> +                                    'Kas Pintxuki',
For now there's no need to change that since the app will be redesigned and this screen has a "Soon" overlay on it.

2022-11-09 07:27 UTC, driels97 commented on lib/features/app_settings_info/screens/my_account_screen.dart
> +                                    'Kas Pintxuki',
![Captura de tela 2022-11-09 042733](https://user-images.githubusercontent.com/38893955/200765858-973c8222-57d5-43e5-a9d1-39a39dd03329.png)

2022-11-09 09:00 UTC, serhii-temchenko approved these changes

2022-11-09 09:36 UTC, merged