Feature/language support
Polkadex-Substrate/polkadex-mobile-app pull request #33
Opened 2021-08-12 12:32 UTC by AdrielVBomfim

This PR creates the necessary files and code to begin work on multiple languages support. Also inserts a language selection widget in initial screen.

https://user-images.githubusercontent.com/38893955/129197162-64fece4d-f608-4283-b52d-bb90d3ea1178.mp4

Will close #24

2021-08-12 15:10 UTC, simonsso commented on lib/features/setup/presentation/screens/intro_screen.dart
> +                                    'England',
The sovereign state  is named the United Kingdom of Great Britain and Northern Ireland, England is country in the Union. 

Except when playing football and Cricket - it is complicated just pick Iceland as default.

2021-08-12 16:32 UTC, AdrielVBomfim commented on lib/features/setup/presentation/screens/intro_screen.dart
> +                                    'England',
Solved, now the app should show the country according to the device localization.

2021-08-12 16:38 UTC, AdrielVBomfim commented on lib/generated/intl/messages_all.dart
> +    case 'en_US':
Yeah, at the moment there's just en_US and pt_BR for placeholding purposes but we can add as many countries/languages as we need. At the moment, the current locale of the app is not changing the language of the app. We can discuss how to manage this in the future since the proposal approved by Gautham was to change the languague of the app in the modal bottom sheet.

2021-08-13 03:32 UTC, simonsso commented on lib/main.dart
> +      Platform.localeName.split('_')[1],
this execute split twice, and there is no check if locale was C instead of en_US

2021-08-13 05:18 UTC, simonsso requested changes

2021-08-13 05:18 UTC, simonsso commented on lib/features/setup/presentation/widgets/select_country_widget.dart
> +                              style: tsS18W400CFF,
This error should depend on geo location and not on language setting

2021-08-13 05:18 UTC, simonsso commented on lib/features/setup/presentation/widgets/select_country_widget.dart
> +class SelectCountryWidget extends StatefulWidget {
This should only be a setting for language. We need to get location from the device

2021-08-13 10:05 UTC, AdrielVBomfim commented
@simonsso @Gauthamastro The design and the PR was made considering that the country and language selection would be related to each other, so I'm honestly confused on what exactly to do. I suggest that we close this PR for now so we can better define the separation between country and languague in the app as well as how the design is going to look like with this separation.

2021-08-13 10:53 UTC, AdrielVBomfim commented on lib/features/setup/presentation/widgets/select_country_widget.dart
> +                              style: tsS18W400CFF,
This widget is not a error exactly, it is in the description of the "select country" modal bottom sheet. If we want to turn this into an error, I think we would have to ask rodolfo to remake this.

2021-08-13 23:22 UTC, simonsso approved these changes
If this is what I was shown yesterday it is good

2021-08-13 23:22 UTC, simonsso commented on lib/generated/intl/messages_all.dart
> +      return null;
Should it not return `en` if locale is not supported?

2021-08-14 01:23 UTC, AdrielVBomfim commented on lib/generated/intl/messages_all.dart
> +      return null;
MaterialApp has some internal logic that sets 'en' by default If the device locale is not supported by the app. The code here was generated through the intl plugin, so it probably uses null value to throw an exception if 'en' does not exist, which the plugin makes sure to generate if it is not present on the project.

2021-08-16 11:32 UTC, merged